Repository ReamLabs/ream, pull requests merged in 2025-04, with the labels that each got.

#286 feat: add database table for checkpoint_states
  crates/common/consensus/src/checkpoint.rs
  crates/storage/src/db.rs
  crates/storage/src/tables/checkpoint_states.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#285 feat: add latest messages table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/latest_messages.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#284 feat: add unrealized justifications table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/mod.rs
  crates/storage/src/tables/unrealized_justifications.rs
Labels: Consensus

#287 feat: add database table for block_timeliness
  crates/storage/src/db.rs
  crates/storage/src/tables/block_timeliness.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#288 feat: add proposer_boost_root table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/mod.rs
  crates/storage/src/tables/proposer_boost_root.rs
Labels: Consensus

#289 feat: add unrealized_finalized_checkpoint table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/mod.rs
  crates/storage/src/tables/unrealized_finalized_checkpoint.rs
Labels: Consensus

#290 feat: add unrealized_justified_checkpoint table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/mod.rs
  crates/storage/src/tables/unrealized_justified_checkpoint.rs
Labels: Consensus

#291 feat: add finalized_checkpoint table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/finalized_checkpoint.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#292 feat: add justified_checkpoint table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/justified_checkpoint.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#293 feat: add genesis_time table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/genesis_time.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#294 feat: add time table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/mod.rs
  crates/storage/src/tables/time.rs
Labels: Consensus

#296 feat: add equivocating_indices table to the database
  crates/storage/src/db.rs
  crates/storage/src/tables/equivocating_indices.rs
  crates/storage/src/tables/mod.rs
Labels: Consensus

#302 feat: implement on_attester_slashing fork choice function
  crates/common/fork_choice/src/handlers.rs
Labels: Consensus

#305 feat: Implement on_tick fork choice function
  crates/common/fork_choice/src/handlers.rs
Labels: Consensus

#303 feat: implement on_attestation fork choice function
  crates/common/fork_choice/src/handlers.rs
Labels: Consensus

#321 feat: implement get_forkchoice_store function
  crates/common/fork_choice/src/handlers.rs
Labels: Consensus

#315 feat: implement /headers
  crates/rpc/src/handlers/block.rs
  crates/rpc/src/handlers/header.rs
  crates/rpc/src/handlers/mod.rs
  crates/rpc/src/routes/beacon.rs
  crates/rpc/src/types/query.rs
Labels: Beacon API

#329 feat: Implemented macro for for_choice and tests
  Cargo.lock
  crates/common/consensus/Cargo.toml
  crates/common/consensus/src/checkpoint.rs
  crates/common/consensus/src/constants.rs
  crates/common/consensus/src/deneb/beacon_block_body.rs
  crates/common/consensus/src/deneb/beacon_state.rs
  crates/common/consensus/src/deneb/execution_payload.rs
  crates/common/consensus/src/execution_engine/blob_versioned_hashes.rs
  crates/common/consensus/src/execution_engine/mock_engine.rs
  crates/common/consensus/src/execution_engine/mod.rs
  crates/common/consensus/src/execution_engine/rpc_types/get_blobs.rs
  crates/common/consensus/src/lib.rs
  crates/common/consensus/src/polynomial_commitments/kzg_commitment.rs
  crates/common/consensus/src/polynomial_commitments/kzg_proof.rs
  crates/common/consensus/src/polynomial_commitments/mod.rs
  crates/common/execution_engine/src/lib.rs
  crates/common/execution_engine/src/rpc_types/get_payload.rs
  crates/common/execution_engine/src/utils.rs
  crates/common/fork_choice/src/blob_sidecar.rs
  crates/common/fork_choice/src/handlers.rs
  crates/common/fork_choice/src/lib.rs
  crates/common/fork_choice/src/store.rs
  crates/common/polynomial_commitments/src/handlers.rs
  testing/ef-tests/Cargo.toml
  testing/ef-tests/src/macros/epoch_processing.rs
  testing/ef-tests/src/macros/fork_choice.rs
  testing/ef-tests/src/macros/mod.rs
  testing/ef-tests/src/macros/operations.rs
  testing/ef-tests/src/macros/rewards.rs
  testing/ef-tests/src/macros/sanity_blocks.rs
  testing/ef-tests/src/macros/sanity_slots.rs
  testing/ef-tests/src/utils.rs
  testing/ef-tests/tests/tests.rs
Labels: Consensus, testing

#339 feat: add blobs_and_proofs table to the database
  crates/common/consensus/src/blob_sidecar.rs
  crates/common/consensus/src/execution_engine/engine_trait.rs
  crates/common/consensus/src/execution_engine/mock_engine.rs
  crates/common/consensus/src/execution_engine/rpc_types/get_blobs.rs
  crates/common/consensus/src/lib.rs
  crates/common/execution_engine/src/lib.rs
  crates/common/fork_choice/src/lib.rs
  crates/common/fork_choice/src/store.rs
  crates/storage/src/db.rs
  crates/storage/src/tables/blobs_and_proofs.rs
  crates/storage/src/tables/mod.rs
  testing/ef-tests/src/macros/fork_choice.rs
Labels: Consensus

#352 feat: add missing spec comments in BeaconState & ForkChoice
  crates/common/consensus/src/electra/beacon_state.rs
  crates/common/fork_choice/src/store.rs
Labels: Consensus

#353 feat: Implemented process_sync_aggregate test
  testing/ef-tests/tests/tests.rs
Labels: testing
